# 데이터 합치기
merge 함수 이용

### kopo_region_mst, kopo_channel_seasonality_new regionMasterData, selectExample 변수에 담으세요

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
regionMasterData = pd.read_csv("./dataset/kopo_region_mst.csv", encoding='ms949')

In [8]:
regionMasterData.head()

  REGIONID REGIONNAME
0      A00     AFRICA
1      A01    AMERICA
2      A02      KOREA
3      A03     GERMAN
4      A04     BRAZIL

In [38]:
channelSeasonalityNewData = pd.read_csv("./dataset/kopo_channel_seasonality_new.csv", encoding='ms949')
channelSeasonalityNewData.head()

  REGIONID    PRODUCT  YEARWEEK      QTY
0      A60   PRODUCT4    201402     71.0
1      A60  PRODUCT59    201402  22275.0
2      A60  PRODUCT34    201402   4463.0
3      A60  PRODUCT47    201402      0.0
4      A60  PRODUCT56    201402     23.0

## 데이터 조인

In [18]:
# how 파라미터 기본값은 inner
mergeResult = pd.merge(channelSeasonalityNewData, regionMasterData,\
    left_on="REGIONID", right_on="REGIONID", how="inner")\
    [["REGIONID", "REGIONNAME","PRODUCT","YEARWEEK","QTY"]]


# 결과 건수
#len(mergeResult)

# 결과
mergeResult

       REGIONID REGIONNAME    PRODUCT  YEARWEEK      QTY
0           A60       THAI   PRODUCT4    201402     71.0
1           A60       THAI  PRODUCT59    201402  22275.0
2           A60       THAI  PRODUCT34    201402   4463.0
3           A60       THAI  PRODUCT47    201402      0.0
4           A60       THAI  PRODUCT56    201402     23.0
5           A60       THAI  PRODUCT57    201402     14.0
6           A60       THAI  PRODUCT12    201402   1186.0
7           A60       THAI   PRODUCT1    201402      7.0
8           A60       THAI  PRODUCT33    201402    101.0
9           A60       THAI  PRODUCT62    201402    336.0
10          A60       THAI  PRODUCT58    201401      0.0
11          A60       THAI  PRODUCT63    201401     63.0
12          A60       THAI   PRODUCT4    201401     16.0
13          A60       THAI  PRODUCT59    201401  18012.0
14          A60       THAI  PRODUCT34    201401   3936.0
15          A60       THAI  PRODUCT47    201401      0.0
16          A60       THAI  PRODUCT56    201401     16.0
17          A60       THAI  PRODUCT57    201401      5.0
18          A60       THAI  PRODUCT12    201401    865.0
19          A60       THAI   PRODUCT1    201401      6.0
20          A60       THAI  PRODUCT33    201401     49.0
21          A60       THAI  PRODUCT62    201401    303.0
22          A60       THAI  PRODUCT58    201402      0.0
23          A60       THAI  PRODUCT63    201402     49.0
24          A60       THAI  PRODUCT58    201403      0.0
25          A60       THAI  PRODUCT63    201403     61.0
26          A60       THAI   PRODUCT4    201403     51.0
27          A60       THAI  PRODUCT59    201403  21682.0
28          A60       THAI  PRODUCT34    201403   4294.0
29          A60       THAI  PRODUCT47    201403      0.0
...         ...        ...        ...       ...      ...
124314      A56       SING  PRODUCT59    201630  43158.0
124315      A56       SING  PRODUCT34    201630   4402.0
124316      A56       SING  PRODUCT40    201630      0.0
124317      A56       SING  PRODUCT47    201630      8.0
124318      A56       SING  PRODUCT60    201630      0.0
124319      A56       SING  PRODUCT56    201630     77.0
124320      A56       SING  PRODUCT57    201630   2244.0
124321      A56       SING  PRODUCT12    201630  17168.0
124322      A56       SING   PRODUCT1    201630      0.0
124323      A56       SING  PRODUCT33    201630    117.0
124324      A56       SING  PRODUCT14    201630      1.0
124325      A56       SING  PRODUCT62    201630   4251.0
124326      A56       SING   PRODUCT2    201627    386.0
124327      A56       SING  PRODUCT58    201627    154.0
124328      A56       SING  PRODUCT63    201627   1093.0
124329      A56       SING  PRODUCT15    201627    149.0
124330      A56       SING   PRODUCT4    201627    462.0
124331      A56       SING  PRODUCT16    201627    839.0
124332      A56       SING  PRODUCT59    201627  41004.0
124333      A56       SING  PRODUCT34    201627   1889.0
124334      A56       SING  PRODUCT40    201627      2.0
124335      A56       SING  PRODUCT47    201627     11.0
124336      A56       SING  PRODUCT60    201627      0.0
124337      A56       SING  PRODUCT56    201627     72.0
124338      A56       SING  PRODUCT57    201627   1332.0
124339      A56       SING  PRODUCT12    201627   9297.0
124340      A56       SING   PRODUCT1    201627      0.0
124341      A56       SING  PRODUCT33    201627    125.0
124342      A56       SING  PRODUCT14    201627      1.0
124343      A56       SING  PRODUCT62    201627   2331.0

[124344 rows x 5 columns]

In [23]:
# how 파라미터 기본값은 inner
mergeResult = pd.merge(channelSeasonalityNewData, regionMasterData,\
    left_on="REGIONID", right_on="REGIONID", how="left")\
    [["REGIONID", "REGIONNAME","PRODUCT","YEARWEEK","QTY"]]


# 결과 건수
len(mergeResult)

# 결과
#mergeResult

124658

In [25]:
mergeResult[mergeResult["REGIONNAME"].isnull()]

       REGIONID REGIONNAME    PRODUCT  YEARWEEK      QTY
176         A77        NaN  PRODUCT12    201404   2628.0
177         A77        NaN   PRODUCT1    201404   1623.0
269         A77        NaN  PRODUCT12    201401   3821.0
270         A77        NaN   PRODUCT1    201401   3580.0
1728        A77        NaN  PRODUCT12    201402   2466.0
1729        A77        NaN   PRODUCT1    201402   2465.0
2711        A77        NaN  PRODUCT12    201405   1442.0
2712        A77        NaN   PRODUCT1    201405   1482.0
3096        A77        NaN  PRODUCT12    201403   2401.0
3097        A77        NaN   PRODUCT1    201403   2205.0
4105        A77        NaN  PRODUCT12    201406   3794.0
4106        A77        NaN   PRODUCT1    201406   4735.0
6259        A77        NaN  PRODUCT12    201407   2409.0
6260        A77        NaN   PRODUCT1    201407   3633.0
6653        A77        NaN  PRODUCT12    201409   2587.0
6654        A77        NaN   PRODUCT1    201409   3293.0
7733        A77        NaN  PRODUCT12    201408   2619.0
7734        A77        NaN   PRODUCT1    201408   4466.0
8644        A77        NaN  PRODUCT12    201410   2038.0
8645        A77        NaN   PRODUCT1    201410   2942.0
9892        A77        NaN  PRODUCT12    201412   1678.0
9893        A77        NaN   PRODUCT1    201412   2061.0
10094       A77        NaN  PRODUCT12    201411   2593.0
10095       A77        NaN   PRODUCT1    201411   3625.0
10784       A77        NaN  PRODUCT12    201413   2816.0
10785       A77        NaN   PRODUCT1    201413   2291.0
11245       A77        NaN  PRODUCT12    201414   2837.0
11246       A77        NaN   PRODUCT1    201414   3117.0
12099       A77        NaN  PRODUCT12    201415   1766.0
12100       A77        NaN   PRODUCT1    201415   1776.0
...         ...        ...        ...       ...      ...
111498      A77        NaN  PRODUCT12    201609   4233.0
111499      A77        NaN   PRODUCT1    201609   3538.0
111700      A77        NaN  PRODUCT12    201637   3002.0
111701      A77        NaN   PRODUCT1    201637   1995.0
113316      A77        NaN  PRODUCT12    201547   5240.0
113317      A77        NaN   PRODUCT1    201547   3076.0
113557      A77        NaN  PRODUCT12    201639  14734.0
113558      A77        NaN   PRODUCT1    201639   3665.0
115842      A77        NaN  PRODUCT12    201618   2780.0
115843      A77        NaN   PRODUCT1    201618   2581.0
117322      A77        NaN  PRODUCT12    201616   4659.0
117323      A77        NaN   PRODUCT1    201616   3573.0
117573      A77        NaN  PRODUCT12    201641   4010.0
117574      A77        NaN   PRODUCT1    201641   3299.0
118386      A77        NaN  PRODUCT12    201638   5583.0
118387      A77        NaN   PRODUCT1    201638   4699.0
118523      A77        NaN  PRODUCT12    201640   3603.0
118524      A77        NaN   PRODUCT1    201640   3021.0
119712      A77        NaN  PRODUCT12    201548   4519.0
119713      A77        NaN   PRODUCT1    201548   3558.0
121416      A77        NaN  PRODUCT12    201642   4292.0
121417      A77        NaN   PRODUCT1    201642   3048.0
122120      A77        NaN  PRODUCT12    201630   7120.0
122121      A77        NaN   PRODUCT1    201630   2918.0
122700      A77        NaN  PRODUCT12    201635   3624.0
122701      A77        NaN   PRODUCT1    201635   2764.0
124466      A77        NaN  PRODUCT12    201634   4019.0
124467      A77        NaN   PRODUCT1    201634   3489.0
124470      A77        NaN  PRODUCT12    201627   3002.0
124471      A77        NaN   PRODUCT1    201627   2713.0

[314 rows x 5 columns]

In [29]:
# A01 데이터 정제
a01data = channelSeasonalityNewData[(channelSeasonalityNewData['REGIONID']=='A01')]
len(a01data)
#a01data

3611

In [41]:
# A71 데이터 정제
import numpy as np
a71data = channelSeasonalityNewData[(channelSeasonalityNewData['REGIONID']=='A70')]

a71data

       REGIONID    PRODUCT  YEARWEEK       QTY
227         A70  PRODUCT58    201404       0.0
228         A70  PRODUCT59    201404     309.0
229         A70  PRODUCT34    201404      60.0
320         A70  PRODUCT58    201401       0.0
321         A70  PRODUCT59    201401     341.0
322         A70  PRODUCT34    201401      66.0
1779        A70  PRODUCT58    201402       0.0
1780        A70  PRODUCT59    201402     334.0
1781        A70  PRODUCT34    201402      84.0
3147        A70  PRODUCT58    201403       0.0
3148        A70  PRODUCT59    201403     298.0
3149        A70  PRODUCT34    201403      67.0
4335        A70  PRODUCT58    201406       0.0
4336        A70  PRODUCT59    201406     367.0
4337        A70  PRODUCT34    201406      53.0
4391        A70  PRODUCT58    201405       0.0
4392        A70  PRODUCT59    201405     351.0
4393        A70  PRODUCT34    201405      46.0
5180        A70  PRODUCT58    201409       0.0
5181        A70  PRODUCT59    201409     165.0
5182        A70  PRODUCT34    201409      28.0
6310        A70  PRODUCT58    201407       0.0
6311        A70  PRODUCT59    201407     315.0
6312        A70  PRODUCT34    201407      44.0
6425        A70  PRODUCT58    201408       0.0
6426        A70  PRODUCT59    201408     276.0
6427        A70  PRODUCT34    201408      33.0
7459        A70  PRODUCT58    201410       0.0
7460        A70  PRODUCT59    201410     139.0
7461        A70  PRODUCT34    201410      33.0
...         ...        ...       ...       ...
119239      A70  PRODUCT34    201609    1669.0
119574      A70  PRODUCT59    201637   99987.0
119575      A70  PRODUCT34    201637    1541.0
119894      A70  PRODUCT58    201544      10.0
119895      A70  PRODUCT59    201544   81717.0
119896      A70  PRODUCT34    201544    2211.0
120539      A70  PRODUCT58    201611     382.0
120540      A70  PRODUCT59    201611  150900.0
120541      A70  PRODUCT34    201611    2864.0
120955      A70  PRODUCT58    201547       6.0
120956      A70  PRODUCT59    201547   69978.0
120957      A70  PRODUCT34    201547    2147.0
121333      A70  PRODUCT58    201639      64.0
121334      A70  PRODUCT59    201639  114569.0
121335      A70  PRODUCT34    201639    1735.0
121528      A70  PRODUCT58    201615     191.0
121529      A70  PRODUCT59    201615   90687.0
121530      A70  PRODUCT34    201615    1594.0
122708      A70  PRODUCT58    201628     193.0
122709      A70  PRODUCT59    201628  123681.0
122710      A70  PRODUCT34    201628    1353.0
122819      A70  PRODUCT58    201631     141.0
122820      A70  PRODUCT59    201631  127926.0
122821      A70  PRODUCT34    201631    9890.0
122983      A70  PRODUCT58    201634     105.0
122984      A70  PRODUCT59    201634  130547.0
122985      A70  PRODUCT34    201634    1955.0
122998      A70  PRODUCT58    201627     129.0
122999      A70  PRODUCT59    201627  122788.0
123000      A70  PRODUCT34    201627    1164.0

[471 rows x 4 columns]

In [45]:
# A71 데이터 정제
import numpy as np
a71data = channelSeasonalityNewData[(channelSeasonalityNewData['REGIONID']=='A70')]

a71data["QTY_NEW"] = np.where(a71data['QTY']<500, 500,a71data['QTY'])
a71data

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

       REGIONID    PRODUCT  YEARWEEK       QTY   QTY_NEW
227         A70  PRODUCT58    201404       0.0     500.0
228         A70  PRODUCT59    201404     309.0     500.0
229         A70  PRODUCT34    201404      60.0     500.0
320         A70  PRODUCT58    201401       0.0     500.0
321         A70  PRODUCT59    201401     341.0     500.0
322         A70  PRODUCT34    201401      66.0     500.0
1779        A70  PRODUCT58    201402       0.0     500.0
1780        A70  PRODUCT59    201402     334.0     500.0
1781        A70  PRODUCT34    201402      84.0     500.0
3147        A70  PRODUCT58    201403       0.0     500.0
3148        A70  PRODUCT59    201403     298.0     500.0
3149        A70  PRODUCT34    201403      67.0     500.0
4335        A70  PRODUCT58    201406       0.0     500.0
4336        A70  PRODUCT59    201406     367.0     500.0
4337        A70  PRODUCT34    201406      53.0     500.0
4391        A70  PRODUCT58    201405       0.0     500.0
4392        A70  PRODUCT59    201405     351.0     500.0
4393        A70  PRODUCT34    201405      46.0     500.0
5180        A70  PRODUCT58    201409       0.0     500.0
5181        A70  PRODUCT59    201409     165.0     500.0
5182        A70  PRODUCT34    201409      28.0     500.0
6310        A70  PRODUCT58    201407       0.0     500.0
6311        A70  PRODUCT59    201407     315.0     500.0
6312        A70  PRODUCT34    201407      44.0     500.0
6425        A70  PRODUCT58    201408       0.0     500.0
6426        A70  PRODUCT59    201408     276.0     500.0
6427        A70  PRODUCT34    201408      33.0     500.0
7459        A70  PRODUCT58    201410       0.0     500.0
7460        A70  PRODUCT59    201410     139.0     500.0
7461        A70  PRODUCT34    201410      33.0     500.0
...         ...        ...       ...       ...       ...
119239      A70  PRODUCT34    201609    1669.0    1669.0
119574      A70  PRODUCT59    201637   99987.0   99987.0
119575      A70  PRODUCT34    201637    1541.0    1541.0
119894      A70  PRODUCT58    201544      10.0     500.0
119895      A70  PRODUCT59    201544   81717.0   81717.0
119896      A70  PRODUCT34    201544    2211.0    2211.0
120539      A70  PRODUCT58    201611     382.0     500.0
120540      A70  PRODUCT59    201611  150900.0  150900.0
120541      A70  PRODUCT34    201611    2864.0    2864.0
120955      A70  PRODUCT58    201547       6.0     500.0
120956      A70  PRODUCT59    201547   69978.0   69978.0
120957      A70  PRODUCT34    201547    2147.0    2147.0
121333      A70  PRODUCT58    201639      64.0     500.0
121334      A70  PRODUCT59    201639  114569.0  114569.0
121335      A70  PRODUCT34    201639    1735.0    1735.0
121528      A70  PRODUCT58    201615     191.0     500.0
121529      A70  PRODUCT59    201615   90687.0   90687.0
121530      A70  PRODUCT34    201615    1594.0    1594.0
122708      A70  PRODUCT58    201628     193.0     500.0
122709      A70  PRODUCT59    201628  123681.0  123681.0
122710      A70  PRODUCT34    201628    1353.0    1353.0
122819      A70  PRODUCT58    201631     141.0     500.0
122820      A70  PRODUCT59    201631  127926.0  127926.0
122821      A70  PRODUCT34    201631    9890.0    9890.0
122983      A70  PRODUCT58    201634     105.0     500.0
122984      A70  PRODUCT59    201634  130547.0  130547.0
122985      A70  PRODUCT34    201634    1955.0    1955.0
122998      A70  PRODUCT58    201627     129.0     500.0
122999      A70  PRODUCT59    201627  122788.0  122788.0
123000      A70  PRODUCT34    201627    1164.0    1164.0

[471 rows x 5 columns]